/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_smilehacker_test_MainActivity */

#ifndef _Included_com_smilehacker_test_MainActivity
#define _Included_com_smilehacker_test_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_smilehacker_test_MainActivity
 * Method:    avformatinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_smilehacker_test_MainActivity_avformatinfo
  (JNIEnv *, jobject);

/*
 * Class:     com_smilehacker_test_MainActivity
 * Method:    avcodecinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_smilehacker_test_MainActivity_avcodecinfo
  (JNIEnv *, jobject);

/*
 * Class:     com_smilehacker_test_MainActivity
 * Method:    avfilterinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_smilehacker_test_MainActivity_avfilterinfo
  (JNIEnv *, jobject);

/*
 * Class:     com_smilehacker_test_MainActivity
 * Method:    configurationinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_smilehacker_test_MainActivity_configurationinfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
